name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (@$AUTHOR) (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  default: minor

categories:
  - title: 'Novidades'
    labels:
      - 'enhancement'

  - title: 'Correções'
    labels:
      - 'fix'

  - title: 'Refatorações'
    labels:
      - 'refactor'

  - title: 'Outras mudanças'
    labels:
      - 'chore'
      - 'documentation'

template: |
  ## O que há de novo: $RESOLVED_VERSION
  
  $CHANGES
